### BIG FAT TODO!


from peewee import *

# Connect to a MySQL database on network.
mysql_db = MySQLDatabase(os.environ['DEFAULT_DB'], user=os.environ['USER_DB'], password=os.environ['PASSWORD_DB'],
                         host='localhost', port=3306)
db = mysql_db

class BaseModel(Model):
    class Meta:
        database = db

# Auto generated by s. anleitung
class Website(BaseModel):
    idwebsite = AutoField(column_name='idWebsite')
    lastcheck = DateTimeField(column_name='lastCheck', null=True)
    url = CharField(null=True)

    class Meta:
        table_name = 'Website'

db.connect()
db.close()  # AM ENDE IMMER !!




#######################################################################################################################




# pip install peewee
from peewee import *

# # Connect to a Postgres database.
# pg_db = PostgresqlDatabase('DB_Name', user='postgres', password='secret',
#                            host='10.1.0.9', port=5432)
# # SQLite database using WAL journal mode and 64MB cache.
# sqlite_db = SqliteDatabase('/path/to/app.db', pragmas=(
#     ('journal_mode', 'wal'),
#     ('cache_size', -1024 * 64)))
# # Connect to a MySQL database on network.
mysql_db = MySQLDatabase('DB_Name', user='defias', password='leckMichDochImArschAlter123!',
                         host='localhost', port=3306)
db = mysql_db
class BaseModel(Model):
    class Meta:
        database = db

# Keep this updated get it with:
# python -m pwiz -e mysql -u defias  -H localhost -p 3306    -P 'leckMichDochImArschAlter123!' cmschecker
#                ^ type      ^ user    ^ host      ^ port   ^ PW                            ^ DB_Name
class MainSiteCmsanbieter(BaseModel):
    checkcounter = IntegerField(column_name='checkCounter')
    currentversion = CharField(column_name='currentVersion')
    name = CharField()
    class Meta:
        table_name = 'main_site_cmsanbieter'

db.connect()
db.close() # AM ENDE IMMER !!

# create table
db.create_tables([MainSiteCmsanbieter, AnotherModel])

@_select/read
grandma = Person.select().where(Person.name == 'Grandma L.').get()
# same as
grandma = Person.get(Person.name == 'Grandma L.')
# select ALL
for person in Person.select():
    print(person.name, person.is_relative)
# select WHERE
query = Pet.select().where(Pet.animal_type == 'cat')
for pet in query:
    print(pet.name, pet.owner.name)
# select KA
query = (Pet.select(Pet, Person).join(Person).where(Pet.animal_type == 'cat').order_by(Pet.name))
for pet in query:
    print(pet.name, pet.owner.name)
    print(pet.name, pet.owners.count(), 'owners')
# FILTER
d1940 = date(1940, 1, 1)
d1960 = date(1960, 1, 1)
query = (Person
         .select()
         .where((Person.birthday < d1940) | (Person.birthday > d1960))
         .where(Person.birthday.between(d1940, d1960)))
for person in query:
    print(person.name, person.birthday)
@_add
uncle_bob = Person(name='Bob', birthday=date(1960, 1, 15), is_relative=True)
# same as
uncle_bob = Person.create(name='Grandma', birthday=date(1935, 3, 1), is_relative=True)
uncle_bob.save()
bob_kitty = Pet.create(owner=uncle_bob, name='Kitty', animal_type='cat')
bob_kitty.save()
@_change
grandma.name = 'Grandma L.'
grandma.save()  # # Update grandma's name in the database. Returns 1
grandma.delete_instance()
herb_fido.owner = uncle_bob         # # change owner !
herb_fido.save()
bob_fido = herb_fido # rename our variable for clarity



def EXAMPLE CMSCHECKER:
    from peewee import *

    # Connect to a MySQL database on network.
    mysql_db = MySQLDatabase('cmschecker', user='defias', password='leckMichDochImArschAlter123!',
                             host='localhost', port=3306)

    db = mysql_db

    class BaseModel(Model):
        class Meta:
            database = db


    class MainSiteWebsites(BaseModel):
        checkcounter = IntegerField(column_name='checkCounter')
        url = CharField()

        class Meta:
            table_name = 'main_site_websites'

    db.connect()


    grandma = MainSiteWebsites.select().where(MainSiteWebsites.url == 'https:#www.youtube.com').get()
    grandma.url = 'ficken.de'
    grandma.save()

    db.close()
